CREATE TABLE weekly_sales_data (
    "Year_Week" TEXT PRIMARY KEY,
    "weekly_avg_repeat_purchases" FLOAT,
    "total_sales" FLOAT,
    "unique_transactions" INTEGER,
    "unique_customers" INTEGER,
    "discounted_transactions" INTEGER,
    "Beverages" FLOAT,
    "Butchers" FLOAT,
    "Computers and electric accessories" FLOAT,
    "Electric household essentials" FLOAT,
    "Food" FLOAT,
    "Furniture" FLOAT,
    "Milk Products" FLOAT,
    "Patisserie" FLOAT,
    "Cash" INTEGER,
    "Credit Card" INTEGER,
    "Digital Wallet" INTEGER,
    "In-store" INTEGER,
    "Online" INTEGER,
    "weekly_avg_repeat_purchases_t-1" FLOAT,
    "weekly_avg_repeat_purchases_t-2" FLOAT,
    "weekly_avg_repeat_purchases_t-3" FLOAT,
    "weekly_avg_repeat_purchases_t-4" FLOAT,
    "weekly_avg_repeat_purchases_t-5" FLOAT,
    "weekly_avg_repeat_purchases_t-6" FLOAT,
    "weekly_avg_repeat_purchases_t-7" FLOAT,
    "weekly_avg_repeat_purchases_t-8" FLOAT,
    "weekly_avg_repeat_purchases_t-9" FLOAT,
    "weekly_avg_repeat_purchases_t-10" FLOAT,
    "weekly_avg_repeat_purchases_t-11" FLOAT,
    "weekly_avg_repeat_purchases_t-12" FLOAT,
    "weekly_avg_repeat_purchases_t-13" FLOAT,
    "weekly_avg_repeat_purchases_t-14" FLOAT,
    "weekly_avg_repeat_purchases_t-15" FLOAT,
    "weekly_avg_repeat_purchases_t-16" FLOAT,
    "weekly_avg_repeat_purchases_t-17" FLOAT,
    "weekly_avg_repeat_purchases_t-18" FLOAT,
    "weekly_avg_repeat_purchases_t-19" FLOAT,
    "weekly_avg_repeat_purchases_t-20" FLOAT,
    "weekly_avg_repeat_purchases_t-21" FLOAT,
    "weekly_avg_repeat_purchases_t-22" FLOAT,
    "weekly_avg_repeat_purchases_t-23" FLOAT,
    "weekly_avg_repeat_purchases_t-24" FLOAT,
    "weekly_avg_repeat_purchases_t-25" FLOAT,
    "weekly_avg_repeat_purchases_t-26" FLOAT,
    "weekly_avg_repeat_purchases_t-27" FLOAT,
    "weekly_avg_repeat_purchases_t-28" FLOAT,
    "weekly_avg_repeat_purchases_t-29" FLOAT,
    "weekly_avg_repeat_purchases_t-30" FLOAT,
    "total_sales_t-1" FLOAT,
    "total_sales_t-2" FLOAT,
    "total_sales_t-3" FLOAT,
    "total_sales_t-4" FLOAT,
    "total_sales_t-5" FLOAT,
    "total_sales_t-6" FLOAT,
    "total_sales_t-7" FLOAT,
    "total_sales_t-8" FLOAT,
    "total_sales_t-9" FLOAT,
    "total_sales_t-10" FLOAT,
    "total_sales_t-11" FLOAT,
    "total_sales_t-12" FLOAT,
    "total_sales_t-13" FLOAT,
    "total_sales_t-14" FLOAT,
    "total_sales_t-15" FLOAT,
    "total_sales_t-16" FLOAT,
    "total_sales_t-17" FLOAT,
    "total_sales_t-18" FLOAT,
    "total_sales_t-19" FLOAT,
    "total_sales_t-20" FLOAT,
    "total_sales_t-21" FLOAT,
    "total_sales_t-22" FLOAT,
    "total_sales_t-23" FLOAT,
    "total_sales_t-24" FLOAT,
    "total_sales_t-25" FLOAT,
    "total_sales_t-26" FLOAT,
    "total_sales_t-27" FLOAT,
    "total_sales_t-28" FLOAT,
    "total_sales_t-29" FLOAT,
    "total_sales_t-30" FLOAT,
    "unique_transactions_t-1" FLOAT,
    "unique_transactions_t-2" FLOAT
);